### ISSUE TITLE
번역에 따른 규칙이 있나요?

### ISSUE THREAD

**Issue by demavend** [mulder21c/html5spec-translate-kr#1]
프로젝트에 기여하고 싶습니다.
번역을 하는 데 있어서 규칙이 있는지 궁금합니다.

**Comment by mulder21c** [comment]
안녕하세요.
그냥 개인적으로 공부할 겸 겸사겸사 번역하면서 아카이브 겸 버전 관리(?)겸 해서 github 페이지를 활용하느라 만든 repository라서 프로젝트 수준으로는 생각을 안해봤습니다 ^^;;;

일단 방법을 생각해봐야 할 부분이라
우선적으로는 cotranslated 브랜치에 push reuqest를 주시는 쪽으로 가닥을 잡으면 될듯 합니다.

cotranslated 브랜치에서는 contributor 가 자유롭게 작업 하도록 하고,
여기서 적절한 번역을 gh-page로 선택적 반영을 하는 방향이 좋지 않을까 생각이 듭니다.
(현재는 이 브랜치가 존재하지 않기 때문에 주말즈음해서 빈 브랜치로 readme 정도만 간략하게 만들어서 올려 놓을 예정입니다.)

규칙은 따로 명시해둔 것은 없습니다.
단지
1. W3C HTML5 Recommendation 2014.10.28 version 페이지를 기준으로 하고
2. 기본 문서를 W3C HTML5 Recommendation 페이지로부터 페이지 소스를 복사해 와서 동일한 파일명으로 생성.
3. 기존의 마크업을 번역본에 그대로 반영하며
4. 번역은 대역의 형태로 한글 - 영문 순으로 둡니다.
5. 한글로 번역한 element에는 lang="ko" 속성을 추가하고, 영문 원문 element 에는 lang="en"을 추가합니다. (스타일 부여와 차후 영문만 보기 / 한글만 보기 / 대역 보기 등의 기능 추가를 위함)

이것 외에는 다른 규칙은 없는 듯 합니다 =ㅁ=a
(그냥 개인저으로 하다보니 머리속에만 혼재되어 존재하는 규칙이랄까요 .... ;;;;;)

감사합니다 ^^

**Comment by demavend** [comment]
감사합니다.
